### ISSUE TITLE
没看懂怎么用

### ISSUE THREAD

**Issue by CoderBQ** [hctym1995/ZLM_ApiDemo#3]
我是做ios的  我想用rtsp推流   这个不是udp比较快一点吗 但是没看懂demo 怎么用     c++的vscode打开报错

**Comment by hctym1995** [comment]
demo是基于zlm的api实现的，哪里看不懂

**Comment by weizi-era** [comment]
demo是属于设备端的吗？实现gb28181信令服务器交互和命令解析

**Comment by hctym1995** [comment]
> demo是属于设备端的吗？实现gb28181信令服务器交互和命令解析

zlm能做的是gb28181中媒体部分的工作，比如RTP的数据收发
信令解析和交互需要单独实现
